
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faEnvelope,
    faHeart
} from '@fortawesome/free-regular-svg-icons';
import {
    faAlignCenter,
    faBarcode,
    faBook,
    faBoxOpen,
    faCalendar,
    faCalendarAlt,
    faCheckCircle,
    faCheckSquare,
    faClipboard,
    faCloud,
    faCode,
    faCog,
    faColumns,
    faCookie,
    faCreditCard,
    faCrosshairs,
    faCube,
    faCubes,
    faDesktop,
    faDollarSign,
    faDownload,
    faExclamationTriangle,
    faFileAlt,
    faFilter,
    faFolder,
    faGift,
    faGlobeEurope,
    faHome,
    faKey,
    faList,
    faNetworkWired,
    faPlus,
    faPuzzlePiece,
    faQuestionCircle,
    faRetweet,
    faSearch,
    faSitemap,
    faSmile,
    faStream,
    faSyncAlt,
    faTasks,
    faThumbtack,
    faUser,
    faUsers,
    faWrench
} from '@fortawesome/free-solid-svg-icons';

library.add(faAlignCenter);
library.add(faBarcode);
library.add(faBook);
library.add(faBoxOpen);
library.add(faCalendar);
library.add(faCalendarAlt);
library.add(faCheckCircle);
library.add(faCheckSquare);
library.add(faClipboard);
library.add(faCloud);
library.add(faCode);
library.add(faCog);
library.add(faColumns);
library.add(faCookie);
library.add(faCreditCard);
library.add(faCrosshairs);
library.add(faCube);
library.add(faCubes);
library.add(faDesktop);
library.add(faDollarSign);
library.add(faDownload);
library.add(faEnvelope);
library.add(faExclamationTriangle);
library.add(faFileAlt);
library.add(faFilter);
library.add(faFolder);
library.add(faGift);
library.add(faGlobeEurope);
library.add(faHeart);
library.add(faHome);
library.add(faKey);
library.add(faPlus);
library.add(faList);
library.add(faNetworkWired);
library.add(faPuzzlePiece);
library.add(faQuestionCircle);
library.add(faRetweet);
library.add(faSearch);
library.add(faSitemap);
library.add(faSmile);
library.add(faStream);
library.add(faSyncAlt);
library.add(faTasks);
library.add(faThumbtack);
library.add(faUser);
library.add(faUsers);
library.add(faWrench);